### ISSUE TITLE
Add Records API Endpoints

### ISSUE THREAD

**Issue by ducksoop** [ducksoop/quickbase-sharp#20]
**Tasks:**
- [x] Add endpoint for [Insert/Update record(s)](https://developer.quickbase.com/operation/upsert)
- [ ] Add endpoint for [Delete record(s)](https://developer.quickbase.com/operation/deleteRecords)
- [ ] Add endpoint for [Query for data](https://developer.quickbase.com/operation/runQuery)
